variable "vpc" {}
variable "vault_token" {}
variable "env" {}
variable "db_servers" {}
variable "zone_id" {}
variable "bastion_nodes" {}
variable "web_servers" {}
variable "app_servers" {}
variable "loadbalancers" {}